"""notification delivery state

Revision ID: 9ffff74acfe3
Revises: c9c9a4ff18be
Create Date: 2026-05-10 23:31:50.994536+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffff74acfe3'
down_revision: Union[str, None] = 'c9c9a4ff18be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        # server_default so adding a NOT NULL column on a non-empty table works on Postgres.
        batch_op.add_column(sa.Column(
            'delivery_attempts', sa.Integer(),
            nullable=False, server_default='0',
        ))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_is_sent'), ['is_sent'], unique=False)

    # Drop the server_default now that all rows have a value; the
    # application supplies the default going forward.
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('delivery_attempts', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_sent'))
        batch_op.drop_column('last_error')
        batch_op.drop_column('delivery_attempts')
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
