"""add scheme_type to cover_plans

Revision ID: 2fe4719f1085
Revises: b2e4a8d1c5f7
Create Date: 2026-05-21 17:52:08.526881+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers (auto-generated by alembic — keep as is)
revision: str = '2fe4719f1085'
down_revision: Union[str, None] = 'b2e4a8d1c5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_SCHEME_VALUES = (
    "funeral", "stokvel", "purchase", "goat_purchase",
    "wedding", "party", "breeding", "farming",
)

# Backfill mapping. Mirrors design spec § 4.3.
# Each row is (category, cover_type or None for all-in-category, scheme_type).
_BACKFILL: list[tuple[str, str | None, str]] = [
    ("me", None, "funeral"),
    ("me_and_family", None, "funeral"),
    ("parents_and_inlaws", None, "funeral"),
    ("extended_family", None, "funeral"),
    ("livestock_benefits", "Cattle during funeral", "funeral"),
    ("livestock_benefits", "Cattle in December", "purchase"),
    ("livestock_benefits", "Sheep in December", "purchase"),
    ("livestock_benefits", "Goat in December", "goat_purchase"),
]


def upgrade() -> None:
    bind = op.get_bind()
    scheme_enum = sa.Enum(*_SCHEME_VALUES, name="schemetype")

    # On Postgres the ENUM type must exist before the column.
    if bind.dialect.name == "postgresql":
        scheme_enum.create(bind, checkfirst=True)

    # 1. Add the column as nullable so we can backfill before constraining it.
    with op.batch_alter_table("cover_plans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scheme_type", scheme_enum, nullable=True))

    # 2. Backfill existing rows.
    for category, cover_type, scheme_type in _BACKFILL:
        if cover_type is None:
            op.execute(
                sa.text(
                    "UPDATE cover_plans SET scheme_type = :st WHERE category = :cat"
                ).bindparams(st=scheme_type, cat=category)
            )
        else:
            op.execute(
                sa.text(
                    "UPDATE cover_plans SET scheme_type = :st "
                    "WHERE category = :cat AND cover_type = :ct"
                ).bindparams(st=scheme_type, cat=category, ct=cover_type)
            )

    # 3. Make it NOT NULL + indexed.
    with op.batch_alter_table("cover_plans", schema=None) as batch_op:
        batch_op.alter_column("scheme_type", existing_type=scheme_enum, nullable=False)
        batch_op.create_index("ix_cover_plans_scheme_type", ["scheme_type"])


def downgrade() -> None:
    with op.batch_alter_table("cover_plans", schema=None) as batch_op:
        batch_op.drop_index("ix_cover_plans_scheme_type")
        batch_op.drop_column("scheme_type")

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="schemetype").drop(bind, checkfirst=True)
